name: SIA WEB
on: push
jobs:
  deploy:
    name: Subir Cambios Laravel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Public
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: c2290501.ferozo.com
          username: sia@ateste.ar
          password: Siatestear1234
          local-dir: 'public/'
          server-dir: '/'

      - uses: actions/checkout@v2
      - name: Upload Laravel
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: c2290501.ferozo.com
          username: ftp@c2290501.ferozo.com
          password: we82fuBOdu
          local-dir: './'
          server-dir: '/siasystem/'
          dry-run: true
          exclude: |
            */.git*
            */.gitattributes*
            **/.git*/**
            **/node_modules/**
            **/public/**
            */.env*
            **/.idea/**
            **/vendor/bin/**
            */artisan*
            **/tests/**
