name: git-ftp-action
  # You may pin to the exact commit or the version.
  # uses: sebastianpopp/git-ftp-action@33a94c0e0fce59ca477baa9d1748a5f2e53fb429
uses: sebastianpopp/git-ftp-action@3.0.0
  with:
  # URL
    url: /home/sistem18/public_html/bicho44/siaproject
  # FTP login name
    user:  bicho44@sistematizar.ar
  # FTP password
    password: bicho44qwe
  # Specifies a local directory to sync from as if it were the git project root path.
    syncroot: # optional, default is .
  # Additional options
    options: # optional, default is --auto-init
