name: SIA WEB a Testear
on: push
jobs:
  deploy:
    name: SIA A Testear
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Upload SIA Public
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: c2290501.ferozo.com
          username: sia@ateste.ar
          password: Siatestear1234
          local-dir: 'public/'
          server-dir: '/'
          exclude: |
            */index.php*

      - uses: actions/checkout@v2
      - name: Upload SIA System
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: c2290501.ferozo.com
          username: ftp@c2290501.ferozo.com
          password: we82fuBOdu
          local-dir: './'
          server-dir: '/public_html/siasystem/'
          exclude: |
            */.git*
            */.gitattributes*
            */.cpanel.yml*
            */.editorconfig*
            */.envatestear*
            */.styleci.yml*
            **/.git*/**
            **/node_modules/**
            **/public/**
            */.env*
            **/.idea/**
            */artisan*
            **/tests/**
            **/vendor/**
            **/bootsrap/cache/.php*/**
            **/storage/logs/.log*/**

      - uses: actions/checkout@v2
      - name: Upload SIA Vendor
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: c2290501.ferozo.com
          username: ftp@c2290501.ferozo.com
          password: we82fuBOdu
          local-dir: './vendor/'
          server-dir: '/public_html/siasystem/vendor/'
          exclude: |
            **/vendor/bin/**
